### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by mostlyobvious** [perplexes/m2r#38] opened 2012-07-31 21:38 UTC
Accroding to [this article](http://www.engineyard.com/blog/2011/concurrency-in-jruby/) that code is not thread-safe: https://github.com/perplexes/m2r/blob/master/lib/m2r.rb#L11

**Comment by paneq** [comment] 2012-08-01 06:35
Duplicate of #37

**Closed as completed by paneq** 2012-08-01 06:35 UTC
